export const obj = {
    autoClear: true,
    clearColor: [0, 0, 0],
    ambientColor: [0, 0, 0],
    gravity: [0, -9.807, 0],
    collisionsEnabled: true,
    useRightHandedSystem: false,
    morphTargetManagers: [],
    lights: [
        {
            tags: null,
            groundColor: [0, 0, 0],
            direction: [0, 1, 0],
            diffuse: [1, 1, 1],
            specular: [1, 1, 1],
            falloffType: 0,
            intensity: 0.5,
            range: 1.7976931348623157e308,
            intensityMode: 0,
            radius: 0.00001,
            _renderPriority: 0,
            shadowEnabled: true,
            excludeWithLayerMask: 0,
            includeOnlyWithLayerMask: 0,
            lightmapMode: 0,
            name: "defaultLight",
            id: "defaultLight",
            state: "",
            uniqueId: 6,
            type: 3,
            animations: [],
            ranges: [],
            isEnabled: true,
        },
    ],

    //     {
    //         "tags": null,
    //         "shadowAngle": 1.5707963267948966,
    //         "diffuse": [
    //             1,
    //             0,
    //             0
    //         ],
    //         "specular": [
    //             1,
    //             1,
    //             1
    //         ],
    //         "falloffType": 0,
    //         "intensity": 1,
    //         "range": 1.7976931348623157e+308,
    //         "intensityMode": 0,
    //         "radius": 0.00001,
    //         "_renderPriority": 0,
    //         "shadowEnabled": true,
    //         "excludeWithLayerMask": 0,
    //         "includeOnlyWithLayerMask": 0,
    //         "lightmapMode": 0,
    //         "position": [
    //             0,
    //             50,
    //             0
    //         ],
    //         "name": "omni",
    //         "id": "omni",
    //         "state": "on",
    //         "uniqueId": 260,
    //         "type": 0,
    //         "animations": [],
    //         "ranges": [],
    //         "isEnabled": true
    //     },
    //     {
    //         "tags": null,
    //         "shadowAngle": 1.5707963267948966,
    //         "diffuse": [
    //             0,
    //             1,
    //             0
    //         ],
    //         "specular": [
    //             1,
    //             1,
    //             1
    //         ],
    //         "falloffType": 0,
    //         "intensity": 1,
    //         "range": 1.7976931348623157e+308,
    //         "intensityMode": 0,
    //         "radius": 0.00001,
    //         "_renderPriority": 0,
    //         "shadowEnabled": true,
    //         "excludeWithLayerMask": 0,
    //         "includeOnlyWithLayerMask": 0,
    //         "lightmapMode": 0,
    //         "position": [
    //             0,
    //             50,
    //             0
    //         ],
    //         "name": "omni",
    //         "id": "omni",
    //         "state": "on",
    //         "uniqueId": 261,
    //         "type": 0,
    //         "animations": [],
    //         "ranges": [],
    //         "isEnabled": true
    //     },
    //     {
    //         "tags": null,
    //         "shadowAngle": 1.5707963267948966,
    //         "diffuse": [
    //             0,
    //             0,
    //             1
    //         ],
    //         "specular": [
    //             1,
    //             1,
    //             1
    //         ],
    //         "falloffType": 0,
    //         "intensity": 1,
    //         "range": 1.7976931348623157e+308,
    //         "intensityMode": 0,
    //         "radius": 0.00001,
    //         "_renderPriority": 0,
    //         "shadowEnabled": true,
    //         "excludeWithLayerMask": 0,
    //         "includeOnlyWithLayerMask": 0,
    //         "lightmapMode": 0,
    //         "position": [
    //             0,
    //             50,
    //             0
    //         ],
    //         "name": "omni",
    //         "id": "omni",
    //         "state": "on",
    //         "uniqueId": 262,
    //         "type": 0,
    //         "animations": [],
    //         "ranges": [],
    //         "isEnabled": true
    //     }
    // ],
    cameras: [
        {
            tags: null,
            alpha: 1.5208379310729538,
            beta: 1.1076479067652332,
            radius: 447.66058571198784,
            target: [0, 0, 0],
            inertialAlphaOffset: 0,
            inertialBetaOffset: 0,
            inertialRadiusOffset: 0,
            lowerBetaLimit: 0.1,
            upperBetaLimit: 1.5550883635269477,
            lowerRadiusLimit: 150,
            inertialPanningX: 0,
            inertialPanningY: 0,
            pinchToPanMaxDistance: 20,
            panningOriginTarget: [0, 0, 0],
            panningInertia: 0.9,
            zoomToMouseLocation: false,
            zoomOnFactor: 1,
            targetScreenOffset: [0, 0],
            allowUpsideDown: true,
            useInputToRestoreState: true,
            rotation: [0, 0, 0],
            speed: 2,
            position: [20, 20, 20],
            upVector: [0, 1, 0],
            fov: 0.8,
            projectionPlaneTilt: 0,
            minZ: 1,
            maxZ: 10000,
            inertia: 0.9,
            mode: 0,
            layerMask: 268435455,
            fovMode: 0,
            cameraRigMode: 0,
            name: "Camera",
            id: "Camera",
            state: "",
            uniqueId: 259,
            type: "UniversalCamera",
            // "inputsmgr": {
            //     "ArcRotateCameraKeyboardMoveInput": {
            //         "tags": null,
            //         "keysUp": [
            //             38
            //         ],
            //         "keysDown": [
            //             40
            //         ],
            //         "keysLeft": [
            //             37
            //         ],
            //         "keysRight": [
            //             39
            //         ],
            //         "keysReset": [
            //             220
            //         ],
            //         "panningSensibility": 50,
            //         "zoomingSensibility": 25,
            //         "useAltToZoom": true,
            //         "angularSpeed": 0.01
            //     },
            //     "ArcRotateCameraMouseWheelInput": {
            //         "tags": null,
            //         "wheelPrecision": 3,
            //         "zoomToMouseLocation": false,
            //         "wheelDeltaPercentage": 0
            //     },
            //     "ArcRotateCameraPointersInput": {
            //         "tags": null,
            //         "buttons": [
            //             0,
            //             1,
            //             2
            //         ],
            //         "angularSensibilityX": 1000,
            //         "angularSensibilityY": 1000,
            //         "pinchPrecision": 12,
            //         "pinchDeltaPercentage": 0,
            //         "useNaturalPinchZoom": false,
            //         "pinchZoom": true,
            //         "panningSensibility": 1000,
            //         "multiTouchPanning": true,
            //         "multiTouchPanAndZoom": true
            //     }
            // },
            animations: [],
            ranges: [],
            isEnabled: true,
        },
    ],
    activeCameraID: "Camera",
    animations: [],
    // materials: [
    //     {
    //         tags: null,
    //         ambient: [0, 0, 0],
    //         diffuse: [1, 1, 1],
    //         specular: [0, 0, 0],
    //         emissive: [0, 0, 0],
    //         specularPower: 64,
    //         useAlphaFromDiffuseTexture: false,
    //         useEmissiveAsIllumination: false,
    //         linkEmissiveWithDiffuse: false,
    //         useSpecularOverAlpha: false,
    //         useReflectionOverAlpha: false,
    //         disableLighting: false,
    //         useObjectSpaceNormalMap: false,
    //         useParallax: false,
    //         useParallaxOcclusion: false,
    //         parallaxScaleBias: 0.05,
    //         roughness: 0,
    //         indexOfRefraction: 0.98,
    //         invertRefractionY: true,
    //         alphaCutOff: 0.4,
    //         useLightmapAsShadowmap: false,
    //         useReflectionFresnelFromSpecular: false,
    //         useGlossinessFromSpecularMapAlpha: false,
    //         maxSimultaneousLights: 4,
    //         invertNormalMapX: false,
    //         invertNormalMapY: false,
    //         twoSidedLighting: false,
    //         applyDecalMapAfterDetailMap: false,
    //         id: "grid",
    //         name: "grid",
    //         checkReadyOnEveryCall: false,
    //         checkReadyOnlyOnce: false,
    //         state: "",
    //         alpha: 1,
    //         backFaceCulling: true,
    //         cullBackFaces: true,
    //         sideOrientation: 1,
    //         alphaMode: 2,
    //         _needDepthPrePass: false,
    //         disableDepthWrite: false,
    //         disableColorWrite: false,
    //         forceDepthWrite: false,
    //         depthFunction: 0,
    //         separateCullingPass: false,
    //         fogEnabled: true,
    //         pointSize: 1,
    //         zOffset: 0,
    //         zOffsetUnits: 0,
    //         pointsCloud: false,
    //         fillMode: 0,
    //         stencil: {
    //             tags: null,
    //             func: 519,
    //             funcRef: 1,
    //             funcMask: 255,
    //             opStencilFail: 7680,
    //             opDepthFail: 7680,
    //             opStencilDepthPass: 7681,
    //             mask: 255,
    //             enabled: false,
    //         },
    //         uniqueId: 265,
    //         plugins: {
    //             DetailMapConfiguration: {
    //                 tags: null,
    //                 diffuseBlendLevel: 1,
    //                 roughnessBlendLevel: 1,
    //                 bumpLevel: 1,
    //                 normalBlendMethod: 0,
    //                 isEnabled: false,
    //                 name: "DetailMap",
    //                 priority: 140,
    //                 registerForExtraEvents: false,
    //             },
    //         },
    //     },
    //     // {
    //     //     tags: null,
    //     //     ambient: [0, 0, 0],
    //     //     diffuse: [0.4, 0.4, 0.4],
    //     //     specular: [0.4, 0.4, 0.4],
    //     //     emissive: [1, 0, 0],
    //     //     specularPower: 64,
    //     //     useAlphaFromDiffuseTexture: false,
    //     //     useEmissiveAsIllumination: false,
    //     //     linkEmissiveWithDiffuse: false,
    //     //     useSpecularOverAlpha: false,
    //     //     useReflectionOverAlpha: false,
    //     //     disableLighting: false,
    //     //     useObjectSpaceNormalMap: false,
    //     //     useParallax: false,
    //     //     useParallaxOcclusion: false,
    //     //     parallaxScaleBias: 0.05,
    //     //     roughness: 0,
    //     //     indexOfRefraction: 0.98,
    //     //     invertRefractionY: true,
    //     //     alphaCutOff: 0.4,
    //     //     useLightmapAsShadowmap: false,
    //     //     useReflectionFresnelFromSpecular: false,
    //     //     useGlossinessFromSpecularMapAlpha: false,
    //     //     maxSimultaneousLights: 4,
    //     //     invertNormalMapX: false,
    //     //     invertNormalMapY: false,
    //     //     twoSidedLighting: false,
    //     //     applyDecalMapAfterDetailMap: false,
    //     //     id: "ground",
    //     //     name: "ground",
    //     //     checkReadyOnEveryCall: false,
    //     //     checkReadyOnlyOnce: false,
    //     //     state: "",
    //     //     alpha: 1,
    //     //     backFaceCulling: true,
    //     //     cullBackFaces: true,
    //     //     sideOrientation: 1,
    //     //     alphaMode: 2,
    //     //     _needDepthPrePass: false,
    //     //     disableDepthWrite: false,
    //     //     disableColorWrite: false,
    //     //     forceDepthWrite: false,
    //     //     depthFunction: 0,
    //     //     separateCullingPass: false,
    //     //     fogEnabled: true,
    //     //     pointSize: 1,
    //     //     zOffset: 0,
    //     //     zOffsetUnits: 0,
    //     //     pointsCloud: false,
    //     //     fillMode: 0,
    //     //     stencil: {
    //     //         tags: null,
    //     //         func: 519,
    //     //         funcRef: 1,
    //     //         funcMask: 255,
    //     //         opStencilFail: 7680,
    //     //         opDepthFail: 7680,
    //     //         opStencilDepthPass: 7681,
    //     //         mask: 255,
    //     //         enabled: false,
    //     //     },
    //     //     uniqueId: 268,
    //     //     plugins: {
    //     //         DetailMapConfiguration: {
    //     //             tags: null,
    //     //             diffuseBlendLevel: 1,
    //     //             roughnessBlendLevel: 1,
    //     //             bumpLevel: 1,
    //     //             normalBlendMethod: 0,
    //     //             isEnabled: false,
    //     //             name: "DetailMap",
    //     //             priority: 140,
    //     //             registerForExtraEvents: false,
    //     //         },
    //     //     },
    //     // },
    //     // {
    //     //     tags: null,
    //     //     ambient: [0, 0, 0],
    //     //     diffuse: [0.4, 0.4, 0.4],
    //     //     specular: [0.4, 0.4, 0.4],
    //     //     emissive: [0, 1, 0],
    //     //     specularPower: 64,
    //     //     useAlphaFromDiffuseTexture: false,
    //     //     useEmissiveAsIllumination: false,
    //     //     linkEmissiveWithDiffuse: false,
    //     //     useSpecularOverAlpha: false,
    //     //     useReflectionOverAlpha: false,
    //     //     disableLighting: false,
    //     //     useObjectSpaceNormalMap: false,
    //     //     useParallax: false,
    //     //     useParallaxOcclusion: false,
    //     //     parallaxScaleBias: 0.05,
    //     //     roughness: 0,
    //     //     indexOfRefraction: 0.98,
    //     //     invertRefractionY: true,
    //     //     alphaCutOff: 0.4,
    //     //     useLightmapAsShadowmap: false,
    //     //     useReflectionFresnelFromSpecular: false,
    //     //     useGlossinessFromSpecularMapAlpha: false,
    //     //     maxSimultaneousLights: 4,
    //     //     invertNormalMapX: false,
    //     //     invertNormalMapY: false,
    //     //     twoSidedLighting: false,
    //     //     applyDecalMapAfterDetailMap: false,
    //     //     id: "ground",
    //     //     name: "ground",
    //     //     checkReadyOnEveryCall: false,
    //     //     checkReadyOnlyOnce: false,
    //     //     state: "",
    //     //     alpha: 1,
    //     //     backFaceCulling: true,
    //     //     cullBackFaces: true,
    //     //     sideOrientation: 1,
    //     //     alphaMode: 2,
    //     //     _needDepthPrePass: false,
    //     //     disableDepthWrite: false,
    //     //     disableColorWrite: false,
    //     //     forceDepthWrite: false,
    //     //     depthFunction: 0,
    //     //     separateCullingPass: false,
    //     //     fogEnabled: true,
    //     //     pointSize: 1,
    //     //     zOffset: 0,
    //     //     zOffsetUnits: 0,
    //     //     pointsCloud: false,
    //     //     fillMode: 0,
    //     //     stencil: {
    //     //         tags: null,
    //     //         func: 519,
    //     //         funcRef: 1,
    //     //         funcMask: 255,
    //     //         opStencilFail: 7680,
    //     //         opDepthFail: 7680,
    //     //         opStencilDepthPass: 7681,
    //     //         mask: 255,
    //     //         enabled: false,
    //     //     },
    //     //     uniqueId: 271,
    //     //     plugins: {
    //     //         DetailMapConfiguration: {
    //     //             tags: null,
    //     //             diffuseBlendLevel: 1,
    //     //             roughnessBlendLevel: 1,
    //     //             bumpLevel: 1,
    //     //             normalBlendMethod: 0,
    //     //             isEnabled: false,
    //     //             name: "DetailMap",
    //     //             priority: 140,
    //     //             registerForExtraEvents: false,
    //     //         },
    //     //     },
    //     // },
    //     // {
    //     //     tags: null,
    //     //     ambient: [0, 0, 0],
    //     //     diffuse: [0.4, 0.4, 0.4],
    //     //     specular: [0.4, 0.4, 0.4],
    //     //     emissive: [0, 0, 1],
    //     //     specularPower: 64,
    //     //     useAlphaFromDiffuseTexture: false,
    //     //     useEmissiveAsIllumination: false,
    //     //     linkEmissiveWithDiffuse: false,
    //     //     useSpecularOverAlpha: false,
    //     //     useReflectionOverAlpha: false,
    //     //     disableLighting: false,
    //     //     useObjectSpaceNormalMap: false,
    //     //     useParallax: false,
    //     //     useParallaxOcclusion: false,
    //     //     parallaxScaleBias: 0.05,
    //     //     roughness: 0,
    //     //     indexOfRefraction: 0.98,
    //     //     invertRefractionY: true,
    //     //     alphaCutOff: 0.4,
    //     //     useLightmapAsShadowmap: false,
    //     //     useReflectionFresnelFromSpecular: false,
    //     //     useGlossinessFromSpecularMapAlpha: false,
    //     //     maxSimultaneousLights: 4,
    //     //     invertNormalMapX: false,
    //     //     invertNormalMapY: false,
    //     //     twoSidedLighting: false,
    //     //     applyDecalMapAfterDetailMap: false,
    //     //     id: "ground",
    //     //     name: "ground",
    //     //     checkReadyOnEveryCall: false,
    //     //     checkReadyOnlyOnce: false,
    //     //     state: "",
    //     //     alpha: 1,
    //     //     backFaceCulling: true,
    //     //     cullBackFaces: true,
    //     //     sideOrientation: 1,
    //     //     alphaMode: 2,
    //     //     _needDepthPrePass: false,
    //     //     disableDepthWrite: false,
    //     //     disableColorWrite: false,
    //     //     forceDepthWrite: false,
    //     //     depthFunction: 0,
    //     //     separateCullingPass: false,
    //     //     fogEnabled: true,
    //     //     pointSize: 1,
    //     //     zOffset: 0,
    //     //     zOffsetUnits: 0,
    //     //     pointsCloud: false,
    //     //     fillMode: 0,
    //     //     stencil: {
    //     //         tags: null,
    //     //         func: 519,
    //     //         funcRef: 1,
    //     //         funcMask: 255,
    //     //         opStencilFail: 7680,
    //     //         opDepthFail: 7680,
    //     //         opStencilDepthPass: 7681,
    //     //         mask: 255,
    //     //         enabled: false,
    //     //     },
    //     //     uniqueId: 274,
    //     //     plugins: {
    //     //         DetailMapConfiguration: {
    //     //             tags: null,
    //     //             diffuseBlendLevel: 1,
    //     //             roughnessBlendLevel: 1,
    //     //             bumpLevel: 1,
    //     //             normalBlendMethod: 0,
    //     //             isEnabled: false,
    //     //             name: "DetailMap",
    //     //             priority: 140,
    //     //             registerForExtraEvents: false,
    //     //         },
    //     //     },
    //     // },
    //     // {
    //     //     tags: null,
    //     //     ambient: [0, 0, 0],
    //     //     diffuse: [0.4, 0.4, 0.4],
    //     //     specular: [0.4, 0.4, 0.4],
    //     //     emissive: [0.5, 0, 0.5],
    //     //     specularPower: 64,
    //     //     useAlphaFromDiffuseTexture: false,
    //     //     useEmissiveAsIllumination: false,
    //     //     linkEmissiveWithDiffuse: false,
    //     //     useSpecularOverAlpha: false,
    //     //     useReflectionOverAlpha: false,
    //     //     disableLighting: false,
    //     //     useObjectSpaceNormalMap: false,
    //     //     useParallax: false,
    //     //     useParallaxOcclusion: false,
    //     //     parallaxScaleBias: 0.05,
    //     //     roughness: 0,
    //     //     indexOfRefraction: 0.98,
    //     //     invertRefractionY: true,
    //     //     alphaCutOff: 0.4,
    //     //     useLightmapAsShadowmap: false,
    //     //     useReflectionFresnelFromSpecular: false,
    //     //     useGlossinessFromSpecularMapAlpha: false,
    //     //     maxSimultaneousLights: 4,
    //     //     invertNormalMapX: false,
    //     //     invertNormalMapY: false,
    //     //     twoSidedLighting: false,
    //     //     applyDecalMapAfterDetailMap: false,
    //     //     id: "ground",
    //     //     name: "ground",
    //     //     checkReadyOnEveryCall: false,
    //     //     checkReadyOnlyOnce: false,
    //     //     state: "",
    //     //     alpha: 1,
    //     //     backFaceCulling: true,
    //     //     cullBackFaces: true,
    //     //     sideOrientation: 1,
    //     //     alphaMode: 2,
    //     //     _needDepthPrePass: false,
    //     //     disableDepthWrite: false,
    //     //     disableColorWrite: false,
    //     //     forceDepthWrite: false,
    //     //     depthFunction: 0,
    //     //     separateCullingPass: false,
    //     //     fogEnabled: true,
    //     //     pointSize: 1,
    //     //     zOffset: 0,
    //     //     zOffsetUnits: 0,
    //     //     pointsCloud: false,
    //     //     fillMode: 0,
    //     //     stencil: {
    //     //         tags: null,
    //     //         func: 519,
    //     //         funcRef: 1,
    //     //         funcMask: 255,
    //     //         opStencilFail: 7680,
    //     //         opDepthFail: 7680,
    //     //         opStencilDepthPass: 7681,
    //     //         mask: 255,
    //     //         enabled: false,
    //     //     },
    //     //     uniqueId: 277,
    //     //     plugins: {
    //     //         DetailMapConfiguration: {
    //     //             tags: null,
    //     //             diffuseBlendLevel: 1,
    //     //             roughnessBlendLevel: 1,
    //     //             bumpLevel: 1,
    //     //             normalBlendMethod: 0,
    //     //             isEnabled: false,
    //     //             name: "DetailMap",
    //     //             priority: 140,
    //     //             registerForExtraEvents: false,
    //     //         },
    //     //     },
    //     // },
    // ],
    multiMaterials: [],
    environmentIntensity: 1,
    skeletons: [],
    transformNodes: [],
    geometries: {
        vertexData: [
            {
                id: "466dd9d4-cb75-49f7-ba74-4ec20358a366",
                uniqueId: 264,
                updatable: false,
                positions: [-500, 0, 500, 500, 0, 500, -500, 0, -500, 500, 0, -500],
                normals: [0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
                uvs: [0, 1, 1, 1, 0, 0, 1, 0],
                indices: [3, 1, 0, 2, 3, 0],
            },
        ],
    },
    // meshes: [
    //     {
    //         name: "grid",
    //         id: "grid",
    //         uniqueId: 263,
    //         type: "gridMesh",
    //         position: [0, 0, 0],
    //         rotation: [0, 0, 0],
    //         scaling: [1, 1, 1],
    //         localMatrix: {
    //             "0": 1,
    //             "1": 0,
    //             "2": 0,
    //             "3": 0,
    //             "4": 0,
    //             "5": 1,
    //             "6": 0,
    //             "7": 0,
    //             "8": 0,
    //             "9": 0,
    //             "10": 1,
    //             "11": 0,
    //             "12": 0,
    //             "13": 0,
    //             "14": 0,
    //             "15": 1,
    //         },
    //         isEnabled: true,
    //         isVisible: true,
    //         infiniteDistance: false,
    //         pickable: true,
    //         receiveShadows: false,
    //         billboardMode: 0,
    //         visibility: 1,
    //         checkCollisions: false,
    //         isBlocker: false,
    //         overrideMaterialSideOrientation: null,
    //         isUnIndexed: false,
    //         geometryUniqueId: 264,
    //         geometryId: "466dd9d4-cb75-49f7-ba74-4ec20358a366",
    //         subMeshes: [
    //             {
    //                 materialIndex: 0,
    //                 verticesStart: 0,
    //                 verticesCount: 4,
    //                 indexStart: 0,
    //                 indexCount: 6,
    //             },
    //         ],
    //         materialUniqueId: 265,
    //         materialId: "ground",
    //         instances: [],
    //         animations: [],
    //         ranges: [],
    //         layerMask: 268435455,
    //         alphaIndex: 1.7976931348623157e308,
    //         hasVertexAlpha: false,
    //         overlayAlpha: 0.5,
    //         overlayColor: [1, 0, 0],
    //         applyFog: true,
    //         subdivisionsX: 1,
    //         subdivisionsY: 1,
    //         minX: -500,
    //         maxX: 500,
    //         minZ: -500,
    //         maxZ: 500,
    //         width: 10000,
    //         height: 10000,
    //     },
    //     // {
    //     //     name: "red",
    //     //     id: "red",
    //     //     uniqueId: 266,
    //     //     type: "Mesh",
    //     //     position: [-100, 0, 0],
    //     //     rotation: [0, 0, 0],
    //     //     scaling: [1, 1, 1],
    //     //     localMatrix: {
    //     //         "0": 1,
    //     //         "1": 0,
    //     //         "2": 0,
    //     //         "3": 0,
    //     //         "4": 0,
    //     //         "5": 1,
    //     //         "6": 0,
    //     //         "7": 0,
    //     //         "8": 0,
    //     //         "9": 0,
    //     //         "10": 1,
    //     //         "11": 0,
    //     //         "12": 0,
    //     //         "13": 0,
    //     //         "14": 0,
    //     //         "15": 1,
    //     //     },
    //     //     isEnabled: true,
    //     //     isVisible: true,
    //     //     infiniteDistance: false,
    //     //     pickable: true,
    //     //     receiveShadows: false,
    //     //     billboardMode: 0,
    //     //     visibility: 1,
    //     //     checkCollisions: false,
    //     //     isBlocker: false,
    //     //     overrideMaterialSideOrientation: null,
    //     //     isUnIndexed: false,
    //     //     geometryUniqueId: 267,
    //     //     geometryId: "2f5b9209-a3b5-4a4a-9d45-e164764f3833",
    //     //     subMeshes: [
    //     //         {
    //     //             materialIndex: 0,
    //     //             verticesStart: 0,
    //     //             verticesCount: 24,
    //     //             indexStart: 0,
    //     //             indexCount: 36,
    //     //         },
    //     //     ],
    //     //     materialUniqueId: 268,
    //     //     materialId: "ground",
    //     //     instances: [],
    //     //     animations: [],
    //     //     ranges: [],
    //     //     layerMask: 268435455,
    //     //     alphaIndex: 1.7976931348623157e308,
    //     //     hasVertexAlpha: false,
    //     //     overlayAlpha: 0.5,
    //     //     overlayColor: [1, 0, 0],
    //     //     applyFog: true,
    //     // },
    //     // {
    //     //     name: "green",
    //     //     id: "green",
    //     //     uniqueId: 269,
    //     //     type: "Mesh",
    //     //     position: [0, 0, -100],
    //     //     rotation: [0, 0, 0],
    //     //     scaling: [1, 1, 1],
    //     //     localMatrix: {
    //     //         "0": 1,
    //     //         "1": 0,
    //     //         "2": 0,
    //     //         "3": 0,
    //     //         "4": 0,
    //     //         "5": 1,
    //     //         "6": 0,
    //     //         "7": 0,
    //     //         "8": 0,
    //     //         "9": 0,
    //     //         "10": 1,
    //     //         "11": 0,
    //     //         "12": 0,
    //     //         "13": 0,
    //     //         "14": 0,
    //     //         "15": 1,
    //     //     },
    //     //     isEnabled: true,
    //     //     isVisible: true,
    //     //     infiniteDistance: false,
    //     //     pickable: true,
    //     //     receiveShadows: false,
    //     //     billboardMode: 0,
    //     //     visibility: 1,
    //     //     checkCollisions: false,
    //     //     isBlocker: false,
    //     //     overrideMaterialSideOrientation: null,
    //     //     isUnIndexed: false,
    //     //     geometryUniqueId: 270,
    //     //     geometryId: "e27f17ab-2d21-41ff-a0a2-11cdc70c1c60",
    //     //     subMeshes: [
    //     //         {
    //     //             materialIndex: 0,
    //     //             verticesStart: 0,
    //     //             verticesCount: 24,
    //     //             indexStart: 0,
    //     //             indexCount: 36,
    //     //         },
    //     //     ],
    //     //     materialUniqueId: 271,
    //     //     materialId: "ground",
    //     //     instances: [],
    //     //     animations: [],
    //     //     ranges: [],
    //     //     layerMask: 268435455,
    //     //     alphaIndex: 1.7976931348623157e308,
    //     //     hasVertexAlpha: false,
    //     //     overlayAlpha: 0.5,
    //     //     overlayColor: [1, 0, 0],
    //     //     applyFog: true,
    //     // },
    //     // {
    //     //     name: "blue",
    //     //     id: "blue",
    //     //     uniqueId: 272,
    //     //     type: "Mesh",
    //     //     position: [100, 0, 0],
    //     //     rotation: [0, 0, 0],
    //     //     scaling: [1, 1, 1],
    //     //     localMatrix: {
    //     //         "0": 1,
    //     //         "1": 0,
    //     //         "2": 0,
    //     //         "3": 0,
    //     //         "4": 0,
    //     //         "5": 1,
    //     //         "6": 0,
    //     //         "7": 0,
    //     //         "8": 0,
    //     //         "9": 0,
    //     //         "10": 1,
    //     //         "11": 0,
    //     //         "12": 0,
    //     //         "13": 0,
    //     //         "14": 0,
    //     //         "15": 1,
    //     //     },
    //     //     isEnabled: true,
    //     //     isVisible: true,
    //     //     infiniteDistance: false,
    //     //     pickable: true,
    //     //     receiveShadows: false,
    //     //     billboardMode: 0,
    //     //     visibility: 1,
    //     //     checkCollisions: false,
    //     //     isBlocker: false,
    //     //     overrideMaterialSideOrientation: null,
    //     //     isUnIndexed: false,
    //     //     geometryUniqueId: 273,
    //     //     geometryId: "863ced76-0395-4cb6-a23c-81a6e5e39433",
    //     //     subMeshes: [
    //     //         {
    //     //             materialIndex: 0,
    //     //             verticesStart: 0,
    //     //             verticesCount: 24,
    //     //             indexStart: 0,
    //     //             indexCount: 36,
    //     //         },
    //     //     ],
    //     //     materialUniqueId: 274,
    //     //     materialId: "ground",
    //     //     instances: [],
    //     //     animations: [],
    //     //     ranges: [],
    //     //     layerMask: 268435455,
    //     //     alphaIndex: 1.7976931348623157e308,
    //     //     hasVertexAlpha: false,
    //     //     overlayAlpha: 0.5,
    //     //     overlayColor: [1, 0, 0],
    //     //     applyFog: true,
    //     // },
    //     // {
    //     //     name: "sphere",
    //     //     id: "sphere",
    //     //     uniqueId: 275,
    //     //     type: "Mesh",
    //     //     position: [0, 0, 100],
    //     //     rotation: [0, 0, 0],
    //     //     scaling: [1, 1, 1],
    //     //     localMatrix: {
    //     //         "0": 1,
    //     //         "1": 0,
    //     //         "2": 0,
    //     //         "3": 0,
    //     //         "4": 0,
    //     //         "5": 1,
    //     //         "6": 0,
    //     //         "7": 0,
    //     //         "8": 0,
    //     //         "9": 0,
    //     //         "10": 1,
    //     //         "11": 0,
    //     //         "12": 0,
    //     //         "13": 0,
    //     //         "14": 0,
    //     //         "15": 1,
    //     //     },
    //     //     isEnabled: true,
    //     //     isVisible: true,
    //     //     infiniteDistance: false,
    //     //     pickable: true,
    //     //     receiveShadows: false,
    //     //     billboardMode: 0,
    //     //     visibility: 1,
    //     //     checkCollisions: false,
    //     //     isBlocker: false,
    //     //     overrideMaterialSideOrientation: null,
    //     //     isUnIndexed: false,
    //     //     geometryUniqueId: 276,
    //     //     geometryId: "99d8dece-3b25-4a93-b774-1d222bd4aee1",
    //     //     subMeshes: [
    //     //         {
    //     //             materialIndex: 0,
    //     //             verticesStart: 0,
    //     //             verticesCount: 703,
    //     //             indexStart: 0,
    //     //             indexCount: 3888,
    //     //         },
    //     //     ],
    //     //     materialUniqueId: 277,
    //     //     materialId: "ground",
    //     //     instances: [],
    //     //     animations: [],
    //     //     ranges: [],
    //     //     layerMask: 268435455,
    //     //     alphaIndex: 1.7976931348623157e308,
    //     //     hasVertexAlpha: false,
    //     //     overlayAlpha: 0.5,
    //     //     overlayColor: [1, 0, 0],
    //     //     applyFog: true,
    //     // },
    //     // {
    //     //     name: "donut",
    //     //     id: "donut",
    //     //     uniqueId: 278,
    //     //     type: "Mesh",
    //     //     position: [0, 0, 0],
    //     //     rotation: [0, 0, 0],
    //     //     scaling: [1, 1, 1],
    //     //     localMatrix: {
    //     //         "0": 1,
    //     //         "1": 0,
    //     //         "2": 0,
    //     //         "3": 0,
    //     //         "4": 0,
    //     //         "5": 1,
    //     //         "6": 0,
    //     //         "7": 0,
    //     //         "8": 0,
    //     //         "9": 0,
    //     //         "10": 1,
    //     //         "11": 0,
    //     //         "12": 0,
    //     //         "13": 0,
    //     //         "14": 0,
    //     //         "15": 1,
    //     //     },
    //     //     isEnabled: true,
    //     //     isVisible: true,
    //     //     infiniteDistance: false,
    //     //     pickable: true,
    //     //     receiveShadows: false,
    //     //     billboardMode: 0,
    //     //     visibility: 1,
    //     //     checkCollisions: false,
    //     //     isBlocker: false,
    //     //     overrideMaterialSideOrientation: null,
    //     //     isUnIndexed: false,
    //     //     geometryUniqueId: 279,
    //     //     geometryId: "e0729b80-b67a-4a6f-96fb-b6bef02166e6",
    //     //     subMeshes: [
    //     //         {
    //     //             materialIndex: 0,
    //     //             verticesStart: 0,
    //     //             verticesCount: 289,
    //     //             indexStart: 0,
    //     //             indexCount: 1734,
    //     //         },
    //     //     ],
    //     //     materialUniqueId: 280,
    //     //     materialId: "default material",
    //     //     instances: [],
    //     //     animations: [],
    //     //     ranges: [],
    //     //     layerMask: 268435455,
    //     //     alphaIndex: 1.7976931348623157e308,
    //     //     hasVertexAlpha: false,
    //     //     overlayAlpha: 0.5,
    //     //     overlayColor: [1, 0, 0],
    //     //     applyFog: true,
    //     // },
    // ],
    particleSystems: [],
    postProcesses: [],
};
